database:
  url: jdbc:mysql://localhost:3306/mydb
  username: dbuser
  password: dbpass

server:
  port: 8080

app:
  mail-server:
    host: smtp.example.com
    port: 587
    username: user@example.com
    password: mailpass
  name: My Application Yml
  version: 1.0.0
  debug: false
  verbose: true
  timeout: 879
  delay: 143
  threshold: 0.678
  frequency: 9.3136
  password: ENC(7082Bgi+1YKARO5sGSrdyJ3Ad0yXfDMazj+l4xaSCt1j3Oi7kq3rf3RB)